services:
  #  postgres:
  #    image: postgres
  #    container_name: postgresgrafana
  #    restart: always
  #    ports:
  #      - '5432:5432'
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #      POSTGRES_DB: grafanadb

  #  adminer:
  #    image: adminer
  #    container_name: adminergrafana
  #    restart: always
  #    ports:
  #      - 8080:8080

  #zipkin
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'

  #prometheus
  prometheus:
    image: prom/prometheus
    container_name: my-promethes-crud
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  #tempo
  my-tempo:
    image: grafana/tempo
    container_name: my-tempo-crud
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "9611:9411"

  #loki
  #my-loki:
    #image: grafana/loki:main
    #container_name: my-loki-crud
    #command: [ "-config.file=/etc/loki/local-config.yaml" ]
    #ports:
      #- "4100:3100"

  #grafana
  my-grafana:
    image: grafana/grafana
    container_name: my-grafana-crud
    restart: unless-stopped
    ports:
      - "3900:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./docker/grafana/:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root