apiVersion: 1

datasources:
  - name: My-Prometheus
    type: prometheus
    access: proxy
    url: http://my-promethes-crud:9090
    isDefault: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: My-Tempo
    type: tempo
    access: proxy
    url: http://my-tempo-crud:3200
    uid: tempo
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
      nodeGraph:
        enabled: true

  #- name: My-Loki
    #type: loki
    #uid: loki
    #access: proxy
    #url: http://my-loki-observability:3100
    #isDefault: true
    #jsonData:
      #derivedFields:
        #- datasourceUid: tempo
          #matcherRegex: \[.+,(.+?)\]
          #name: TraceID
          #url: $${__value.raw}